name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ "3.2", "3.3", "3.4" ]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0 # fetch all history, needed for fixture repo
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: tests
      run: bin/test
    - name: rubocop
      run: bundle exec rubocop
